name = "ppt_factorization"
version = "0.1.0"
defaultTargets = ["ppt_factorization"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#145f3f493e7ffbb45994424a5d1e3a84a7f57a38"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "PptFactorization"

[[lean_lib]]
name = "EnsX2026"

[[lean_exe]]
name = "ppt_factorization"
root = "Main"
