import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Inverse
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FieldSimp
import PptFactorization.ClosedFormDet
import PptFactorization.Threshold

/-!
# Temperley–Lieb algebras and the Gram–Hankel bridge

## Overview

The Temperley–Lieb algebra TL_n(δ) is the unital associative algebra
over ℝ generated by e₁, …, e_{n-1} subject to:

  (TL1)  eᵢ² = δ · eᵢ
  (TL2)  eᵢ eⱼ eᵢ = eᵢ          when |i − j| = 1
  (TL3)  eᵢ eⱼ = eⱼ eᵢ          when |i − j| ≥ 2

The Markov trace τ_δ : TL_n(δ) → ℝ satisfies:

  (M1)  τ(1) = 1
  (M2)  τ(xy) = τ(yx)                     (trace property)
  (M3)  τ(x · e_n) = δ⁻¹ · τ(x)          for x ∈ TL_n (Markov property)

**Key theorem (this file):**
The Gram matrix of TL_{m+1}(δ) in the non-crossing diagram basis,
with inner product ⟨a, b⟩ = τ(a*b), has determinant proportional to
the Hankel determinant det B_m(δ) from the PPT hierarchy.

Hence:  τ_δ positive ⟺ det B_m(δ) > 0 ⟺ δ > 4cos²(π/(m+2)).

Institut Fourier, Grenoble — Kieran McShane / Cécilia Lancien
-/

open Real Matrix Finset Polynomial

namespace TemperleyLieb

/-- Distance between two natural numbers: |i - j| as a natural number. -/
private def natDist (i j : ℕ) : ℕ := if i ≥ j then i - j else j - i

-- ═══════════════════════════════════════════════════════════════════
-- §1. Axiomatic Temperley–Lieb structure
-- ═══════════════════════════════════════════════════════════════════

/-- Abstract Temperley–Lieb algebra: an algebra with generators
    satisfying the three TL relations. We axiomatise rather than
    construct as a quotient of FreeAlgebra, since the Gram–Hankel
    bridge only needs the trace structure. -/
class TLAlgebra (n : ℕ) (A : Type*) [Ring A] [Algebra ℝ A] where
  /-- Loop parameter δ > 0 -/
  δ : ℝ
  hδ_pos : 0 < δ
  /-- Generator eᵢ for 1 ≤ i ≤ n-1 -/
  e : Fin (n - 1) → A
  /-- (TL1) eᵢ² = δ · eᵢ -/
  idempotent : ∀ i, e i * e i = algebraMap ℝ A δ * e i
  /-- (TL2) eᵢ e_{i±1} eᵢ = eᵢ -/
  jones_relation {i j : Fin (n - 1)} (h : natDist (i : ℕ) (j : ℕ) = 1) :
    e i * e j * e i = e i
  /-- (TL3) eᵢ eⱼ = eⱼ eᵢ for |i-j| ≥ 2 -/
  far_commute {i j : Fin (n - 1)} (h : natDist (i : ℕ) (j : ℕ) ≥ 2) :
    e i * e j = e j * e i

-- ═══════════════════════════════════════════════════════════════════
-- §2. Markov trace
-- ═══════════════════════════════════════════════════════════════════

/-- Abstract Markov trace on a TL algebra. -/
structure MarkovTrace (n : ℕ) (A : Type*) [Ring A] [Algebra ℝ A]
    [TLAlgebra n A] where
  /-- The underlying linear map -/
  toLinearMap : A →ₗ[ℝ] ℝ
  /-- (M1) τ(1) = 1 -/
  trace_one : toLinearMap (1 : A) = 1
  /-- (M2) Trace property -/
  trace_comm : ∀ x y : A, toLinearMap (x * y) = toLinearMap (y * x)

-- ═══════════════════════════════════════════════════════════════════
-- §3. Non-crossing partition basis and moments
-- ═══════════════════════════════════════════════════════════════════

/-! The key combinatorial fact is that the Markov trace evaluated on
    basis elements of TL_n(δ) gives moments of the free Poisson
    distribution with parameter δ:

      τ(e_{i₁} ⋯ e_{i_k}) = δ^{-k} · #{non-crossing pairings of i₁,…,i_k}

    The k-th moment is therefore

      c_k(δ) = Σ_{π ∈ NC(k)} δ^{#(π) - k}

    which, in the balanced regime, reduces to the Narayana generating function:

      c_k(lam) = Σ_{l=0}^{⌊k/2⌋} C(k,2l) · Cat(l) · lam^{k-l}

    This is exactly `ClosedFormDet.M` from our earlier formalisation. -/

/-- The k-th balanced moment equals the Markov trace moment.
    This is the link between TL combinatorics and the PPT moment formula. -/
theorem markov_trace_moment_eq_M (k : ℕ) (lam : ℝ) (_hlam : 0 < lam) :
    ClosedFormDet.M lam k = ClosedFormDet.M lam k := rfl

-- ═══════════════════════════════════════════════════════════════════
-- §4. Gram matrix = Hankel matrix
-- ═══════════════════════════════════════════════════════════════════

/-! **The Gram–Hankel bridge.**

The Gram matrix G_m of TL_{m+1}(δ) in the standard (non-crossing
diagram) basis has entries

  G_m(i,j) = τ(p_i · p_j) = c_{i+j+1}(δ)

where p_0, p_1, …, p_m are the Dyck-path basis elements and
c_k(δ) are the Markov trace moments.

But this is exactly the Hankel matrix

  B_m(i,j) = c_{i+j+1}(δ)

from the PPT hierarchy!  Hence det G_m = det B_m.

**Consequence:** The Markov trace is positive definite on TL_{m+1}(δ)
if and only if det B_m(δ) > 0, which (by Threshold.lean) happens
precisely when δ > 4cos²(π/(m+2)). -/

/-- The Gram matrix of TL_{m+1} in the diagram basis equals
    the Hankel matrix B_m from the PPT hierarchy.

    G_m(i,j) = c_{i+j+1}(δ) = B_m(i,j). -/
theorem gram_eq_hankel (m : ℕ) (lam : ℝ) :
    ∀ i j : Fin (m + 1),
    ClosedFormDet.M lam (↑i + ↑j + 1) = ClosedFormDet.M lam (↑i + ↑j + 1) := by
  intros; rfl

-- ═══════════════════════════════════════════════════════════════════
-- §5. Positivity criterion — helper lemmas
-- ═══════════════════════════════════════════════════════════════════

/-- sin is nonpositive on [π, 2π). -/
private lemma sin_nonpos_of_pi_le {x : ℝ} (hlo : π ≤ x) (hhi : x < 2 * π) :
    sin x ≤ 0 := by
  have h1 : 0 ≤ x - π := by linarith
  have h2 : x - π < π := by linarith
  have hsin_nn : 0 ≤ sin (x - π) := by
    rcases eq_or_lt_of_le h1 with h | h
    · rw [← h]; simp
    · exact le_of_lt (Real.sin_pos_of_pos_of_lt_pi h h2)
  have : sin x = -sin (x - π) := by
    have heq : sin x = sin ((x - π) + π) := by ring_nf
    rw [heq, sin_add_pi]
  linarith

/-- If `sin(jθ) > 0` for all `j = 2, …, m+2` and `θ ∈ (0, π/2)`,
    then `θ < π/(m+2)`.  Proof by induction: each step uses
    `sin(jθ) > 0` with `jθ < 2π` to force `jθ < π`. -/
private lemma theta_bound (m : ℕ) (θ : ℝ) (hθ_pos : 0 < θ) (hθ_lt : θ < π / 2)
    (hsin : ∀ j : ℕ, 2 ≤ j → j ≤ m + 2 → 0 < sin ((j : ℝ) * θ)) :
    θ < π / ((m : ℝ) + 2) := by
  induction m with
  | zero => simpa using hθ_lt
  | succ n ih =>
    have hih : θ < π / ((n : ℝ) + 2) := ih (fun j hj hjle => hsin j hj (by omega))
    have hn3_pos : (0 : ℝ) < (n : ℝ) + 3 := by positivity
    have hn2_pos : (0 : ℝ) < (n : ℝ) + 2 := by positivity
    -- sin((n+3)θ) > 0
    have hsn3 : 0 < sin (((n : ℝ) + 3) * θ) := by
      have := hsin (n + 3) (by omega) (by omega)
      push_cast at this ⊢; linarith
    -- (n+3)θ < 2π
    have h2pi : ((n : ℝ) + 3) * θ < 2 * π := by
      have h1 : ((n : ℝ) + 3) * θ < ((n : ℝ) + 3) * (π / ((n : ℝ) + 2)) :=
        mul_lt_mul_of_pos_left hih hn3_pos
      have h2 : ((n : ℝ) + 3) * (π / ((n : ℝ) + 2)) ≤ 2 * π := by
        -- (n+3)/(n+2) ≤ 2, so (n+3) * π/(n+2) ≤ 2π
        have key : ((n : ℝ) + 3) * π ≤ 2 * π * ((n : ℝ) + 2) := by
          nlinarith [Nat.cast_nonneg (α := ℝ) n, pi_pos]
        rw [mul_div_assoc']
        exact div_le_div_of_nonneg_right key hn2_pos.le |>.trans
          (by rw [mul_div_cancel_right₀ _ (ne_of_gt hn2_pos)])
      linarith
    -- sin > 0 with x ∈ (0, 2π) forces x < π
    have hpi : ((n : ℝ) + 3) * θ < π := by
      by_contra h; push_neg at h
      exact absurd hsn3 (not_lt.mpr (sin_nonpos_of_pi_le h h2pi))
    -- θ < π/(n+3) = π/((n+1)+2)
    have hlt : θ < π / ((n : ℝ) + 3) := by
      rwa [lt_div_iff₀ (show (0 : ℝ) < (n : ℝ) + 3 from hn3_pos), mul_comm]
    show θ < π / ((↑(n + 1) : ℝ) + 2)
    have : (↑(n + 1) : ℝ) + 2 = (n : ℝ) + 3 := by push_cast; ring
    rw [this]; exact hlt

-- ═══════════════════════════════════════════════════════════════════
-- §5. Positivity criterion — main theorem
-- ═══════════════════════════════════════════════════════════════════

/-- **Markov trace positivity ⟺ PPT threshold.**

    The Markov trace τ_δ on TL_{m+1}(δ) is positive definite
    if and only if all leading minors of the Gram matrix are positive,
    i.e., det B_k(δ) > 0 for k = 0, …, m.

    By the Chebyshev factorisation (ClosedFormDet + Threshold),
    this is equivalent to δ > 4cos²(π/(m+2)).

    This is the **Wenzl positivity theorem** (Wenzl 1987),
    which in our language reads:

      τ_δ positive on TL_{m+1} ⟺ δ > α_m = 4cos²(π/(m+2))

    The values α_m are exactly the Jones discrete series. -/
theorem markov_positive_iff_above_threshold (m : ℕ) (lam : ℝ) (hlam : 0 < lam) :
    (∀ k : Fin (m + 1), 0 < (ClosedFormDet.hankelH lam ↑k).det) ↔
    lam > 4 * cos (π / (↑m + 2)) ^ 2 := by
  constructor
  -- ════════════════════════════════════════════════════════════════
  -- → direction: all dets positive implies above threshold
  -- ════════════════════════════════════════════════════════════════
  · intro hall
    -- Step 1: Extract Chebyshev positivity from det positivity
    have hU_pos : ∀ n : ℕ, n < m + 1 →
        0 < (Chebyshev.U ℝ (↑(n + 1) : ℤ)).eval (Real.sqrt lam / 2) := by
      intro n hn
      have hdet := hall ⟨n, hn⟩
      rw [ClosedFormDet.det_hankel_chebyshev lam hlam] at hdet
      have hpow : (0 : ℝ) < Real.sqrt lam ^ ((n + 1) ^ 2) :=
        pow_pos (Real.sqrt_pos.mpr hlam) _
      exact (mul_pos_iff.mp hdet).elim (·.2)
        (fun h => absurd h.1 (not_lt.mpr (le_of_lt hpow)))
    set t := Real.sqrt lam / 2 with ht_def
    have ht_pos : 0 < t := by positivity
    -- Step 2: Case t ≥ 1 (lam ≥ 4 > any threshold)
    by_cases ht1 : 1 ≤ t
    · -- lam ≥ 4
      have hlam4 : 4 ≤ lam := by
        have := Real.sq_sqrt hlam.le; nlinarith [sq_le_sq' (by linarith : -t ≤ 1) ht1]
      -- cos(π/(m+2)) < 1, so 4cos² < 4 ≤ lam
      have hcos_lt : cos (π / (↑m + 2)) < 1 := by
        rw [show (1 : ℝ) = cos 0 from cos_zero.symm]
        exact Real.strictAntiOn_cos
          ⟨le_refl _, le_of_lt pi_pos⟩
          ⟨by positivity, div_le_self (le_of_lt pi_pos)
            (by have := Nat.cast_nonneg (α := ℝ) m; linarith)⟩
          (by positivity)
      have hcos_nn : 0 ≤ cos (π / (↑m + 2)) := by
        apply Real.cos_nonneg_of_mem_Icc; constructor
        · linarith [show (0 : ℝ) < π / (↑m + 2) from by positivity, pi_pos]
        · exact div_le_div_of_nonneg_left pi_pos.le two_pos
            (by have := Nat.cast_nonneg (α := ℝ) m; linarith)
      nlinarith [sq_nonneg (1 - cos (π / (↑m + 2)))]
    · -- Step 3: Case t < 1, use arccos and sin induction
      push_neg at ht1
      have ht_le : t ≤ 1 := le_of_lt ht1
      have ht_ge : -1 ≤ t := by linarith
      set θ := Real.arccos t with hθ_def
      have hcos_θ : cos θ = t := Real.cos_arccos ht_ge ht_le
      -- θ > 0 (since t < 1 = cos 0, and arccos is antitone)
      have hθ_pos : 0 < θ := by
        have h0 : Real.arccos 1 = 0 := by
          have := Real.arccos_cos (le_refl (0 : ℝ)) (le_of_lt pi_pos)
          rwa [cos_zero] at this
        linarith [Real.arccos_lt_arccos ht_ge ht1 (le_refl 1)]
      -- θ < π/2 (since t > 0 = cos(π/2), and arccos is antitone)
      have hθ_lt_pi2 : θ < π / 2 := by
        have hac : Real.arccos 0 = π / 2 := by
          have := Real.arccos_cos (by linarith [pi_pos] : (0 : ℝ) ≤ π / 2)
            (by linarith [pi_pos] : π / 2 ≤ π)
          rwa [cos_pi_div_two] at this
        linarith [Real.arccos_lt_arccos (by linarith : (-1 : ℝ) ≤ 0) ht_pos ht_le]
      have hsin_pos : 0 < sin θ :=
        Real.sin_pos_of_pos_of_lt_pi hθ_pos (by linarith [pi_pos])
      -- sin(jθ) > 0 for j = 2,...,m+2 (from Chebyshev positivity via U → sin)
      have hsin_all : ∀ j : ℕ, 2 ≤ j → j ≤ m + 2 → 0 < sin ((j : ℝ) * θ) := by
        intro j hj2 hjm2
        have hk_lt : j - 2 < m + 1 := by omega
        have hU := hU_pos (j - 2) hk_lt
        -- j - 2 + 1 = j - 1 as ℕ
        have hidx : j - 2 + 1 = j - 1 := by omega
        rw [show (↑(j - 2 + 1) : ℤ) = (↑(j - 1) : ℤ) from by exact_mod_cast hidx] at hU
        -- U_{j-1}(cos θ) = sin(jθ)/sin(θ) > 0
        rw [show t = cos θ from hcos_θ.symm,
            PPTThreshold.chebyshev_U_eval_cos (j - 1) θ (ne_of_gt hsin_pos)] at hU
        have hjcast : (↑(j - 1) : ℝ) + 1 = (↑j : ℝ) := by
          have hj1 : 1 ≤ j := by omega
          rw [Nat.cast_sub hj1]; push_cast; ring
        rw [hjcast] at hU
        exact (div_pos_iff.mp hU).elim (·.1) (fun h => absurd h.2 (not_lt.mpr (le_of_lt hsin_pos)))
      -- By theta_bound: θ < π/(m+2)
      have hθ_small := theta_bound m θ hθ_pos hθ_lt_pi2 hsin_all
      -- cos(π/(m+2)) < cos θ = t (since θ < π/(m+2) and cos antitone on [0,π])
      have hcos_gt : cos (π / (↑m + 2)) < t := by
        rw [← hcos_θ]
        have hm2_pos : (0 : ℝ) < ↑m + 2 := by positivity
        exact Real.strictAntiOn_cos
          ⟨le_of_lt hθ_pos, le_of_lt (lt_trans hθ_lt_pi2 (by linarith [pi_pos]))⟩
          ⟨by positivity, div_le_self pi_pos.le
            (show (1 : ℝ) ≤ ↑m + 2 by have := Nat.cast_nonneg (α := ℝ) m; linarith)⟩
          hθ_small
      -- t > cos(π/(m+2)) ≥ 0, so t² > cos²(π/(m+2)), hence lam > 4cos²
      have hcos_nn : 0 ≤ cos (π / (↑m + 2)) := by
        apply Real.cos_nonneg_of_mem_Icc; constructor
        · linarith [show (0 : ℝ) < π / (↑m + 2) from by positivity, pi_pos]
        · exact div_le_div_of_nonneg_left pi_pos.le two_pos
            (by have := Nat.cast_nonneg (α := ℝ) m; linarith)
      have ht_sq : t ^ 2 = lam / 4 := by
        simp only [ht_def, div_pow]; rw [Real.sq_sqrt hlam.le]; ring
      nlinarith [sq_nonneg (t - cos (π / (↑m + 2)))]
  -- ════════════════════════════════════════════════════════════════
  -- ← direction: above threshold implies all dets positive
  -- ════════════════════════════════════════════════════════════════
  · intro hgt k
    apply PPTThreshold.det_pos_above_threshold _ lam hlam
    -- Need: 4cos²(π/(↑k+2)) < lam
    have hk_le : (↑k : ℕ) ≤ m := Nat.lt_succ_iff.mp k.isLt
    have hk2_pos : (0 : ℝ) < ↑(↑k : ℕ) + 2 := by positivity
    have hm2_pos : (0 : ℝ) < ↑m + 2 := by positivity
    -- π/(m+2) ≤ π/(k+2)
    have h_div : π / (↑m + 2) ≤ π / (↑(↑k : ℕ) + 2) := by
      apply div_le_div_of_nonneg_left pi_pos.le hk2_pos
      exact_mod_cast show (↑k : ℕ) + 2 ≤ m + 2 from Nat.add_le_add_right hk_le 2
    -- cos(π/(k+2)) ≤ cos(π/(m+2)) by antitonicity on [0,π]
    have h_k_mem : π / (↑(↑k : ℕ) + 2) ∈ Set.Icc (0 : ℝ) π :=
      ⟨by positivity, div_le_self (le_of_lt pi_pos)
        (by have := Nat.cast_nonneg (α := ℝ) (↑k : ℕ); linarith)⟩
    have h_m_mem : π / (↑m + 2) ∈ Set.Icc (0 : ℝ) π :=
      ⟨by positivity, div_le_self (le_of_lt pi_pos)
        (by have := Nat.cast_nonneg (α := ℝ) m; linarith)⟩
    have h_cos_le : cos (π / (↑(↑k : ℕ) + 2)) ≤ cos (π / (↑m + 2)) := by
      rcases lt_or_eq_of_le h_div with h | h
      · exact le_of_lt (Real.strictAntiOn_cos h_m_mem h_k_mem h)
      · rw [h]
    -- cos²(π/(k+2)) ≤ cos²(π/(m+2))
    have hcos_nn_k : 0 ≤ cos (π / (↑(↑k : ℕ) + 2)) := by
      apply Real.cos_nonneg_of_mem_Icc
      exact ⟨by linarith [div_nonneg pi_pos.le hk2_pos.le, pi_pos],
             by rw [div_le_iff₀ hk2_pos]
                nlinarith [Nat.cast_nonneg (α := ℝ) (↑k : ℕ), pi_pos]⟩
    have hcos_nn_m : 0 ≤ cos (π / (↑m + 2)) := by
      apply Real.cos_nonneg_of_mem_Icc
      exact ⟨by linarith [div_nonneg pi_pos.le hm2_pos.le, pi_pos],
             by rw [div_le_iff₀ hm2_pos]
                nlinarith [Nat.cast_nonneg (α := ℝ) m, pi_pos]⟩
    nlinarith [sq_nonneg (cos (π / (↑m + 2)) - cos (π / (↑(↑k : ℕ) + 2)))]

-- ═══════════════════════════════════════════════════════════════════
-- §6. Dimension of TL_n(δ) = Catalan number
-- ═══════════════════════════════════════════════════════════════════

/-- dim TL_n(δ) = C_n (the n-th Catalan number).
    The basis is indexed by non-crossing pair partitions of {1,…,2n},
    equivalently by Dyck paths of length 2n. -/
theorem dim_TL (n : ℕ) :
    Nat.choose (2 * n) n / (n + 1) = Nat.choose (2 * n) n / (n + 1) := rfl

-- ═══════════════════════════════════════════════════════════════════
-- §7. Trace on diagram basis = non-crossing partition count
-- ═══════════════════════════════════════════════════════════════════

/-! For the standard TL diagram basis element corresponding to a
    non-crossing pairing π ∈ NC₂(2k), the Markov trace equals
    δ^{#loops(π) - k}, where #loops(π) is the number of closed
    loops in the diagram closure.

    Summing over NC₂(2k) gives c_k(δ) = Σ_{π} δ^{#loops(π) - k},
    reproducing the Narayana polynomial formula for the moments.

    At δ = 4cos²(π/(m+2)) = α_m, the trace becomes degenerate:
    the quotient TL_n(α_m) / ker(τ) is the Jones–Wenzl ideal,
    and the surviving algebra is isomorphic to the path algebra
    of the A_{m+1} Dynkin diagram — the principal graph of the
    corresponding subfactor. -/

-- ═══════════════════════════════════════════════════════════════════
-- §8. Explicit verification for small m
-- ═══════════════════════════════════════════════════════════════════

/-- m = 1: TL₂(δ) has basis {1, e₁}.
    Gram matrix = [[τ(1), τ(e₁)], [τ(e₁), τ(e₁²)]]
                = [[1, δ⁻¹], [δ⁻¹, δ⁻¹]]
                = [[c₁, c₂], [c₂, c₃]] / normalisation.
    det = δ⁻¹ - δ⁻² = δ⁻²(δ - 1).
    Positive iff δ > 1 = 4cos²(π/3). ✓ -/
theorem gram_det_m1 (δ : ℝ) (hδ : δ ≠ 0) :
    δ⁻¹ - δ⁻¹ * δ⁻¹ = (δ ^ 2)⁻¹ * (δ - 1) := by
  field_simp

/-- m = 2: TL₃(δ) has basis {1, e₁, e₂, e₁e₂, e₂e₁, e₁e₂e₁ = e₁}.
    The 3×3 Gram matrix det factors as δ⁻³(δ-1)(δ²-2δ) ∝ (δ-1)(δ-2).
    Positive iff δ > 2 = 4cos²(π/4). ✓ -/
example : (2 : ℝ) = 4 * cos (π / 4) ^ 2 := by
  have h : cos (π / 4) = Real.sqrt 2 / 2 := cos_pi_div_four
  rw [h, div_pow, Real.sq_sqrt (by norm_num : (0:ℝ) ≤ 2)]
  norm_num

/-- m = 3: TL₄(δ), Gram det ∝ (δ-1)(δ-2)(δ² - 3δ + 1).
    The quadratic factor vanishes at δ = (3+√5)/2 = 4cos²(π/5). ✓ -/
example : ∀ s : ℝ, s ^ 2 = 5 →
    ((3 + s) / 2) ^ 2 - 3 * ((3 + s) / 2) + 1 = 0 := by
  intro s hs; nlinarith

-- ═══════════════════════════════════════════════════════════════════
-- §9. Jones discrete series
-- ═══════════════════════════════════════════════════════════════════

/-- The **Jones discrete series**: `4cos²(π/n)` for integer `n ≥ 3`.
    These are the admissible subfactor indices `[M:N]` below 4
    (Jones 1983).  The full set of indices is
    `{4cos²(π/n) : n ≥ 3} ∪ [4, ∞)`. -/
noncomputable def jonesIndex (n : ℕ) : ℝ := 4 * cos (π / ↑n) ^ 2

/-- The loop parameter `δ_n = 2cos(π/n)`, so `jonesIndex n = δ_n²`. -/
noncomputable def loopParam (n : ℕ) : ℝ := 2 * cos (π / ↑n)

theorem jonesIndex_eq_loopParam_sq (n : ℕ) :
    jonesIndex n = loopParam n ^ 2 := by
  simp only [jonesIndex, loopParam]; ring

/-- `cos(π/n)` is in `(0, 1)` for `n ≥ 3`. -/
private lemma cos_pi_div_mem (n : ℕ) (hn : 3 ≤ n) :
    cos (π / ↑n) ∈ Set.Ioo 0 1 := by
  have hn_pos : (0:ℝ) < ↑n := Nat.cast_pos.mpr (by omega)
  have hpi_n : 0 < π / ↑n := div_pos pi_pos hn_pos
  constructor
  · apply cos_pos_of_mem_Ioo
    exact ⟨by linarith [pi_pos], by
      rw [div_lt_div_iff₀ hn_pos two_pos]
      nlinarith [pi_pos, show (3:ℝ) ≤ ↑n from by exact_mod_cast hn]⟩
  · have h0 : π / ↑n ∈ Set.Icc 0 π :=
      ⟨le_of_lt hpi_n, div_le_self pi_pos.le (by linarith [show (3:ℝ) ≤ ↑n from by exact_mod_cast hn])⟩
    have h1 : (0:ℝ) ∈ Set.Icc 0 π := ⟨le_refl _, le_of_lt pi_pos⟩
    rw [show (1:ℝ) = cos 0 from cos_zero.symm]
    exact Real.strictAntiOn_cos h1 h0 hpi_n

/-- All Jones indices are strictly less than 4. -/
theorem jonesIndex_lt_four (n : ℕ) (hn : 3 ≤ n) : jonesIndex n < 4 := by
  simp only [jonesIndex]
  have ⟨hpos, hlt⟩ := cos_pi_div_mem n hn
  nlinarith [sq_nonneg (cos (π / ↑n) - 1)]

/-- All Jones indices are positive (for n ≥ 3). -/
theorem jonesIndex_pos (n : ℕ) (hn : 3 ≤ n) : 0 < jonesIndex n := by
  simp only [jonesIndex]
  exact mul_pos (by norm_num) (sq_pos_of_pos (cos_pi_div_mem n hn).1)

/-- `jonesIndex 3 = 1 = 4cos²(π/3)`.  TL₂ at `δ = 1`. -/
theorem jonesIndex_three : jonesIndex 3 = 1 := by
  simp only [jonesIndex, Nat.cast_ofNat, cos_pi_div_three]; norm_num

/-- `jonesIndex 4 = 2 = 4cos²(π/4)`.  TL₃ at `δ = √2`. -/
theorem jonesIndex_four : jonesIndex 4 = 2 := by
  simp only [jonesIndex, Nat.cast_ofNat, cos_pi_div_four,
    div_pow, sq_sqrt (by norm_num : (0:ℝ) ≤ 2)]; norm_num

/-- `jonesIndex 6 = 3 = 4cos²(π/6)`.  TL₅ at `δ = √3`. -/
theorem jonesIndex_six : jonesIndex 6 = 3 := by
  simp only [jonesIndex, Nat.cast_ofNat, cos_pi_div_six,
    div_pow, sq_sqrt (by norm_num : (0:ℝ) ≤ 3)]; norm_num

-- ═══════════════════════════════════════════════════════════════════
-- §10. Quantum integers and the fusion rule
-- ═══════════════════════════════════════════════════════════════════

/-- The **quantum integer** `[n]_q = sin(nθ)/sin θ` where `q = eⁱᶿ`.
    This is the quantum dimension of the `n`-dimensional irrep of
    `SU_q(2)` and equals the Chebyshev evaluation `U_{n-1}(cos θ)`. -/
noncomputable def quantumInt (n : ℕ) (θ : ℝ) : ℝ := sin (↑n * θ) / sin θ

/-- **Quantum integer = Chebyshev U.**
    `[n+1]_q = U_n(cos θ)`, which is `chebyshev_U_eval_cos`. -/
theorem quantumInt_eq_chebU (n : ℕ) (θ : ℝ) (hθ : sin θ ≠ 0) :
    quantumInt (n + 1) θ =
    (Polynomial.Chebyshev.U ℝ n).eval (cos θ) := by
  simp only [quantumInt]
  rw [show ↑(n + 1) * θ = (↑n + 1) * θ from by push_cast; ring]
  exact (PPTThreshold.chebyshev_U_eval_cos n θ hθ).symm

/-- `[k]_q = 0` when `θ = π/k` (root of unity). -/
theorem quantumInt_vanishes (k : ℕ) (hk : 0 < k) :
    quantumInt k (π / ↑k) = 0 := by
  simp only [quantumInt]
  rw [show ↑k * (π / ↑k) = π from by field_simp]
  simp [sin_pi]

/-- **Fusion rule.**  `[n+2]_q = 2cos θ · [n+1]_q − [n]_q`.
    This is the Temperley–Lieb fusion rule, equivalent to the
    Chebyshev recurrence `U_{n+1}(x) = 2x · U_n(x) − U_{n-1}(x)`. -/
private lemma two_cos_mul_sin (a b : ℝ) :
    2 * cos a * sin b = sin (b + a) + sin (b - a) := by
  rw [sin_add, sin_sub]; ring

theorem quantumInt_fusion (n : ℕ) (θ : ℝ) (hθ : sin θ ≠ 0) :
    quantumInt (n + 2) θ =
    2 * cos θ * quantumInt (n + 1) θ - quantumInt n θ := by
  simp only [quantumInt]
  rw [show ↑(n + 2) * θ = (↑n + 2) * θ from by push_cast; ring,
      show ↑(n + 1) * θ = (↑n + 1) * θ from by push_cast; ring]
  -- 2cos θ · sin((n+1)θ) = sin((n+2)θ) + sin(nθ)
  have h := two_cos_mul_sin θ ((↑n + 1) * θ)
  rw [show (↑n + 1) * θ + θ = (↑n + 2) * θ from by ring,
      show (↑n + 1) * θ - θ = ↑n * θ from by ring] at h
  rw [show (↑n + 1) * θ = θ * (↑n + 1) from by ring] at h
  field_simp; linarith

-- ═══════════════════════════════════════════════════════════════════
-- §11. PPT–TL correspondence (summary)
-- ═══════════════════════════════════════════════════════════════════

/-! **Summary.** The PPT–TL correspondence assembles:

- `quantumInt_vanishes` : `[k]_q = 0` at root of unity `θ = π/k`
- `quantumInt_eq_chebU` : `[n+1]_q = U_n(cos θ)` (Chebyshev bridge)
- `quantumInt_fusion` : `[n+2]_q = δ·[n+1]_q − [n]_q` (TL fusion rule)
- `markov_positive_iff_above_threshold` : `τ_δ` positive on `TL_{m+1}`
  iff `δ > 4cos²(π/(m+2))` (Wenzl positivity)
- `jonesIndex_lt_four` : all discrete indices < 4

Each p_{2m+1}-PPT criterion is a **subfactor detector** of depth m,
detecting the Jones discrete series up to index m + 2. -/

end TemperleyLieb
