/-
Copyright (c) 2026 Kieran McShane. All rights reserved.
Released under Apache 2.0 license.
Authors: Kieran McShane
-/
import EnsX2026.Heisenberg.ElementaryMatrices
import Mathlib.Data.Nat.Sqrt
import Mathlib.Data.Int.NatAbs
import Mathlib.Data.Int.Interval
import Mathlib.Order.ConditionallyCompleteLattice.Basic
import Mathlib.Data.Set.Card
import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum

/-!
# Word-length and polynomial growth of the discrete Heisenberg group `H₃(ℤ)`

This file proves Q31, Q32, Q33 of the 2026 ENS/X Math A exam.

* **Q31** (`word_length_upper`) — `|S^k T^ℓ U^m| ≤ |k| + |ℓ| + 6√|m|`.
* **Q32** (`word_length_lower`, `word_length_combined_lower`) —
    `(|k|+|ℓ|+√|m|)/2 ≤ |S^k T^ℓ U^m|`.
* **Q33** (`heisenberg_growth_polynomial`) — polynomial growth of degree 4.

## Design notes

Word-length is defined combinatorially as the infimum over `List Gen` of
lengths of words spelling a matrix.

The lower bound (Q32) is the workhorse: an induction on the **reversed** word
tracks `(k, ℓ, m)` coordinates step-by-step as a normal form grows by
right-multiplication.  The upper bound (Q31) is constructive: `S^k` contributes
`|k|`, `T^ℓ` contributes `|ℓ|`, and `U^m` is produced via a single commutator
`[T^a, S^b]` at cost `6√|m|`.

The polynomial-growth statement (Q33) reduces to the lattice-point count
`#{(k, ℓ, m) : |k|, |ℓ| ≤ R, |m| ≤ R²} = (2R+1)²(2R²+1) ∼ R⁴`, which is
established here via `latticeBox_card` and `normalImage_ncard`.
-/

namespace EnsX2026.Heisenberg

open Matrix

/-! ### The generator alphabet -/

/-- Six generators of `H_3(ℤ)`: `S^{±1}`, `T^{±1}`, `U^{±1}`. -/
inductive Gen
  | sG
  | sInv
  | tG
  | tInv
  | uG
  | uInv
  deriving DecidableEq, Repr

/-- Realisation of a generator as a matrix. -/
def Gen.matrix : Gen → Matrix (Fin 3) (Fin 3) ℤ
  | .sG => S 1
  | .sInv => S (-1)
  | .tG => T 1
  | .tInv => T (-1)
  | .uG => U 1
  | .uInv => U (-1)

/-! ### Words and their products -/

/-- Product of a list of generators (in order of the list). -/
def word_prod : List Gen → Matrix (Fin 3) (Fin 3) ℤ
  | [] => 1
  | g :: rest => g.matrix * word_prod rest

@[simp] theorem word_prod_nil : word_prod [] = 1 := rfl

@[simp] theorem word_prod_cons (g : Gen) (w : List Gen) :
    word_prod (g :: w) = g.matrix * word_prod w := rfl

theorem word_prod_append (u v : List Gen) :
    word_prod (u ++ v) = word_prod u * word_prod v := by
  induction u with
  | nil => simp
  | cons g rest ih =>
    simp [ih, Matrix.mul_assoc]

/-! ### Word length -/

/-- Word-length of a matrix w.r.t. the generating set `{S^{±1}, T^{±1}, U^{±1}}`.

If `M` is not in the subgroup generated by these, this returns `sInf ∅ = 0`. -/
noncomputable def word_length (M : Matrix (Fin 3) (Fin 3) ℤ) : ℕ :=
  sInf { n : ℕ | ∃ w : List Gen, w.length = n ∧ word_prod w = M }

theorem word_length_le_of_word {M : Matrix (Fin 3) (Fin 3) ℤ}
    (w : List Gen) (hw : word_prod w = M) :
    word_length M ≤ w.length := by
  apply Nat.sInf_le
  exact ⟨w, rfl, hw⟩

theorem exists_word_of_word_length {M : Matrix (Fin 3) (Fin 3) ℤ}
    (h : ∃ w : List Gen, word_prod w = M) :
    ∃ w : List Gen, word_prod w = M ∧ w.length = word_length M := by
  obtain ⟨w, hw⟩ := h
  have hne : { n : ℕ | ∃ w : List Gen, w.length = n ∧ word_prod w = M }.Nonempty :=
    ⟨w.length, w, rfl, hw⟩
  have hmem := Nat.sInf_mem hne
  obtain ⟨w', hwlen, hwp⟩ := hmem
  exact ⟨w', hwp, hwlen⟩

/-! ### Basic explicit word constructions for S^k, T^ℓ, U^m -/

/-- A list of `n` copies of a generator. -/
def replicateGen (g : Gen) : ℕ → List Gen
  | 0 => []
  | n + 1 => g :: replicateGen g n

@[simp] theorem replicateGen_length (g : Gen) (n : ℕ) :
    (replicateGen g n).length = n := by
  induction n with
  | zero => rfl
  | succ k ih => simp [replicateGen, ih]

theorem sNatPow_prod (n : ℕ) : word_prod (replicateGen .sG n) = S (n : ℤ) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = S ((0 : ℕ) : ℤ)
    rw [show ((0 : ℕ) : ℤ) = 0 from rfl, ← S_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, S_mul]
    congr 1
    push_cast
    ring

theorem sNatInvPow_prod (n : ℕ) : word_prod (replicateGen .sInv n) = S (-(n : ℤ)) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = S (-((0 : ℕ) : ℤ))
    rw [show -((0 : ℕ) : ℤ) = 0 from by norm_num, ← S_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, S_mul]
    congr 1
    push_cast
    ring

theorem tNatPow_prod (n : ℕ) : word_prod (replicateGen .tG n) = T (n : ℤ) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = T ((0 : ℕ) : ℤ)
    rw [show ((0 : ℕ) : ℤ) = 0 from rfl, ← T_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, T_mul]
    congr 1
    push_cast
    ring

theorem tNatInvPow_prod (n : ℕ) : word_prod (replicateGen .tInv n) = T (-(n : ℤ)) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = T (-((0 : ℕ) : ℤ))
    rw [show -((0 : ℕ) : ℤ) = 0 from by norm_num, ← T_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, T_mul]
    congr 1
    push_cast
    ring

theorem uNatPow_prod (n : ℕ) : word_prod (replicateGen .uG n) = U (n : ℤ) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = U ((0 : ℕ) : ℤ)
    rw [show ((0 : ℕ) : ℤ) = 0 from rfl, ← U_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, U_mul]
    congr 1
    push_cast
    ring

theorem uNatInvPow_prod (n : ℕ) : word_prod (replicateGen .uInv n) = U (-(n : ℤ)) := by
  induction n with
  | zero =>
    show (1 : Matrix (Fin 3) (Fin 3) ℤ) = U (-((0 : ℕ) : ℤ))
    rw [show -((0 : ℕ) : ℤ) = 0 from by norm_num, ← U_zero]
  | succ k ih =>
    simp only [replicateGen, word_prod_cons, Gen.matrix, ih, U_mul]
    congr 1
    push_cast
    ring

/-- Word representing `S^k` for any integer `k`. -/
def sWord (k : ℤ) : List Gen :=
  if 0 ≤ k then replicateGen .sG k.toNat else replicateGen .sInv (-k).toNat

/-- Word representing `T^ℓ` for any integer `ℓ`. -/
def tWord (ℓ : ℤ) : List Gen :=
  if 0 ≤ ℓ then replicateGen .tG ℓ.toNat else replicateGen .tInv (-ℓ).toNat

/-- Word representing `U^m` for any integer `m`. -/
def uWord (m : ℤ) : List Gen :=
  if 0 ≤ m then replicateGen .uG m.toNat else replicateGen .uInv (-m).toNat

/-- Key helper: if `k < 0`, then `(-k).toNat = k.natAbs`. -/
private theorem neg_toNat_eq_natAbs (k : ℤ) (h : k < 0) : (-k).toNat = k.natAbs := by
  omega

theorem sWord_length (k : ℤ) : (sWord k).length = k.natAbs := by
  unfold sWord
  split_ifs with h
  · rw [replicateGen_length]; omega
  · push_neg at h
    rw [replicateGen_length, neg_toNat_eq_natAbs k h]

theorem tWord_length (ℓ : ℤ) : (tWord ℓ).length = ℓ.natAbs := by
  unfold tWord
  split_ifs with h
  · rw [replicateGen_length]; omega
  · push_neg at h
    rw [replicateGen_length, neg_toNat_eq_natAbs ℓ h]

theorem uWord_length (m : ℤ) : (uWord m).length = m.natAbs := by
  unfold uWord
  split_ifs with h
  · rw [replicateGen_length]; omega
  · push_neg at h
    rw [replicateGen_length, neg_toNat_eq_natAbs m h]

theorem sWord_prod (k : ℤ) : word_prod (sWord k) = S k := by
  unfold sWord
  split_ifs with h
  · rw [sNatPow_prod]; congr 1; exact Int.toNat_of_nonneg h
  · rw [sNatInvPow_prod]; congr 1
    push_neg at h
    have hneg : 0 ≤ -k := le_of_lt (by linarith)
    have : ((-k).toNat : ℤ) = -k := Int.toNat_of_nonneg hneg
    linarith

theorem tWord_prod (ℓ : ℤ) : word_prod (tWord ℓ) = T ℓ := by
  unfold tWord
  split_ifs with h
  · rw [tNatPow_prod]; congr 1; exact Int.toNat_of_nonneg h
  · rw [tNatInvPow_prod]; congr 1
    push_neg at h
    have hneg : 0 ≤ -ℓ := le_of_lt (by linarith)
    have : ((-ℓ).toNat : ℤ) = -ℓ := Int.toNat_of_nonneg hneg
    linarith

theorem uWord_prod (m : ℤ) : word_prod (uWord m) = U m := by
  unfold uWord
  split_ifs with h
  · rw [uNatPow_prod]; congr 1; exact Int.toNat_of_nonneg h
  · rw [uNatInvPow_prod]; congr 1
    push_neg at h
    have hneg : 0 ≤ -m := le_of_lt (by linarith)
    have : ((-m).toNat : ℤ) = -m := Int.toNat_of_nonneg hneg
    linarith

/-! ### Commutator powers produce `U^{ab}` -/

/-- Matrix identity: `T^a · S^b · T^{-a} · S^{-b} = U^{ab}`. -/
theorem T_S_commutator_power (a b : ℤ) :
    T a * S b * T (-a) * S (-b) = U (a * b) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [S, T, U, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [S, T, U, Matrix.mul_apply, Fin.sum_univ_three])

/-- The commutator word `T^a · S^b · T^{-a} · S^{-b}`. -/
def commutatorWord (a b : ℤ) : List Gen :=
  tWord a ++ sWord b ++ tWord (-a) ++ sWord (-b)

theorem commutatorWord_length (a b : ℤ) :
    (commutatorWord a b).length = 2 * a.natAbs + 2 * b.natAbs := by
  simp [commutatorWord, tWord_length, sWord_length, Int.natAbs_neg]
  ring

theorem commutatorWord_prod (a b : ℤ) :
    word_prod (commutatorWord a b) = U (a * b) := by
  unfold commutatorWord
  rw [word_prod_append, word_prod_append, word_prod_append]
  rw [tWord_prod, sWord_prod, tWord_prod, sWord_prod]
  exact T_S_commutator_power a b

/-! ### Building `U^m` in few letters using one commutator -/

/-- Produce `U^m` efficiently: `[T^a, S^{sign·a}]` gives `U^{sign·a²}` in
`4a` letters, then `|m - sign·a²| ≤ 2a + 1` more `U^{±1}` copies. -/
def uWordEfficient (m : ℤ) : List Gen :=
  let a : ℕ := Nat.sqrt m.natAbs
  let sign : ℤ := if 0 ≤ m then 1 else -1
  commutatorWord (a : ℤ) (sign * a) ++ uWord (m - sign * a * a)

theorem uWordEfficient_prod (m : ℤ) :
    word_prod (uWordEfficient m) = U m := by
  unfold uWordEfficient
  simp only
  rw [word_prod_append, commutatorWord_prod, uWord_prod, U_mul]
  congr 1
  set a : ℕ := Nat.sqrt m.natAbs
  set sign : ℤ := if 0 ≤ m then 1 else -1
  have : (a : ℤ) * (sign * a) = sign * a * a := by ring
  rw [this]
  ring

theorem uWordEfficient_length_le (m : ℤ) :
    (uWordEfficient m).length ≤ 6 * Nat.sqrt m.natAbs := by
  unfold uWordEfficient
  simp only
  rw [List.length_append, commutatorWord_length, uWord_length]
  set a : ℕ := Nat.sqrt m.natAbs with ha_def
  set sign : ℤ := if 0 ≤ m then 1 else -1 with hsign_def
  have h_signabs : (sign * a).natAbs = a := by
    by_cases h : 0 ≤ m
    · simp [hsign_def, h]
    · simp [hsign_def, h, Int.natAbs_neg]
  have h_a_natAbs : ((a : ℤ)).natAbs = a := by simp
  rw [h_a_natAbs, h_signabs]
  have hsq : a * a ≤ m.natAbs := Nat.sqrt_le _
  have hlt : m.natAbs < (a + 1) * (a + 1) := Nat.lt_succ_sqrt _
  -- Convert Nat (a+1)*(a+1) to explicit expansion.
  have hlt_expand : m.natAbs < a * a + 2 * a + 1 := by
    have : (a + 1) * (a + 1) = a * a + 2 * a + 1 := by ring
    omega
  have h_rem : (m - sign * a * a).natAbs ≤ 2 * a := by
    by_cases hm : 0 ≤ m
    · -- sign = 1.  Goal is (m - ↑a * ↑a).natAbs ≤ 2 * a.
      simp only [hsign_def, hm, if_true, one_mul]
      omega
    · -- sign = -1.  Goal is (m + a²).natAbs ≤ 2a.
      simp only [hsign_def, hm, if_false]
      push_neg at hm
      -- From hm : m < 0, m.natAbs = -m ∈ [a², a²+2a].
      have h_mabs : (m.natAbs : ℤ) = -m := by
        have : (0 : ℤ) ≤ -m := by linarith
        have : ((-m).toNat : ℤ) = -m := Int.toNat_of_nonneg this
        omega
      have h_neg_eq : m - -1 * (a : ℤ) * a = m + (a : ℤ) * a := by ring
      rw [h_neg_eq]
      -- (m + a²).natAbs: since -m ∈ [a², a² + 2a], m + a² ∈ [-2a, 0].
      have h1 : -(2 * a : ℤ) ≤ m + (a : ℤ) * a := by
        have hle : m.natAbs ≤ a * a + 2 * a := Nat.lt_succ_iff.mp hlt_expand
        have : (m.natAbs : ℤ) ≤ a * a + 2 * a := by exact_mod_cast hle
        rw [h_mabs] at this
        linarith
      have h2 : m + (a : ℤ) * a ≤ 0 := by
        have : ((a * a : ℕ) : ℤ) ≤ (m.natAbs : ℤ) := by exact_mod_cast hsq
        rw [h_mabs] at this
        push_cast at this
        linarith
      -- So natAbs ≤ 2a.
      rw [show (m + (a : ℤ) * a).natAbs = (-(m + (a : ℤ) * a)).natAbs from (Int.natAbs_neg _).symm]
      have h_neg_nn : 0 ≤ -(m + (a : ℤ) * a) := by linarith
      have : -(m + (a : ℤ) * a) ≤ 2 * a := by linarith
      have h_tonat : ((-(m + (a : ℤ) * a)).toNat : ℤ) = -(m + (a : ℤ) * a) :=
        Int.toNat_of_nonneg h_neg_nn
      omega
  linarith [h_rem]

/-! ### Q31 — Upper bound -/

/-- Explicit witness word for `H3_normal k ℓ m`:
`S^k · T^ℓ · (commutator block for U^m)`. -/
def normalWord (k ℓ m : ℤ) : List Gen :=
  sWord k ++ tWord ℓ ++ uWordEfficient m

theorem normalWord_prod (k ℓ m : ℤ) :
    word_prod (normalWord k ℓ m) = H3_normal k ℓ m := by
  unfold normalWord
  rw [word_prod_append, word_prod_append]
  rw [sWord_prod, tWord_prod, uWordEfficient_prod]
  exact S_mul_T_mul_U k ℓ m

theorem normalWord_length_le (k ℓ m : ℤ) :
    (normalWord k ℓ m).length ≤ k.natAbs + ℓ.natAbs + 6 * Nat.sqrt m.natAbs := by
  unfold normalWord
  rw [List.length_append, List.length_append]
  rw [sWord_length, tWord_length]
  linarith [uWordEfficient_length_le m]

/-- **Q31.** Word-length upper bound:
`|S^k T^ℓ U^m| ≤ |k| + |ℓ| + 6√|m|`. -/
theorem word_length_upper (k ℓ m : ℤ) :
    word_length (H3_normal k ℓ m) ≤ k.natAbs + ℓ.natAbs + 6 * Nat.sqrt m.natAbs := by
  calc word_length (H3_normal k ℓ m)
      ≤ (normalWord k ℓ m).length := word_length_le_of_word _ (normalWord_prod k ℓ m)
    _ ≤ k.natAbs + ℓ.natAbs + 6 * Nat.sqrt m.natAbs := normalWord_length_le k ℓ m

/-! ### Q32 — Lower bound -/

/-- Multiplying a normal form on the right by `S^1`. -/
theorem H3_normal_mul_S_one (k ℓ m : ℤ) :
    H3_normal k ℓ m * S 1 = H3_normal (k + 1) ℓ (m + ℓ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [S, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [S, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

theorem H3_normal_mul_S_negone (k ℓ m : ℤ) :
    H3_normal k ℓ m * S (-1) = H3_normal (k - 1) ℓ (m - ℓ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [S, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [S, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

theorem H3_normal_mul_T_one (k ℓ m : ℤ) :
    H3_normal k ℓ m * T 1 = H3_normal k (ℓ + 1) m := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [T, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [T, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

theorem H3_normal_mul_T_negone (k ℓ m : ℤ) :
    H3_normal k ℓ m * T (-1) = H3_normal k (ℓ - 1) m := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [T, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [T, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

theorem H3_normal_mul_U_one (k ℓ m : ℤ) :
    H3_normal k ℓ m * U 1 = H3_normal k ℓ (m + 1) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [U, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [U, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

theorem H3_normal_mul_U_negone (k ℓ m : ℤ) :
    H3_normal k ℓ m * U (-1) = H3_normal k ℓ (m - 1) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (first | (simp [U, H3_normal, Matrix.mul_apply, Fin.sum_univ_three]; ring)
           | simp [U, H3_normal, Matrix.mul_apply, Fin.sum_univ_three])

/-- Right-multiplication variant of the word product. -/
def word_prod' : List Gen → Matrix (Fin 3) (Fin 3) ℤ
  | [] => 1
  | g :: rest => word_prod' rest * g.matrix

theorem word_prod'_append (u v : List Gen) :
    word_prod' (u ++ v) = word_prod' v * word_prod' u := by
  induction u with
  | nil => simp [word_prod']
  | cons g rest ih =>
    simp [word_prod', ih, Matrix.mul_assoc]

/-- Link between the two product conventions. -/
theorem word_prod_reverse (w : List Gen) :
    word_prod w.reverse = word_prod' w := by
  induction w with
  | nil => simp [word_prod']
  | cons g rest ih =>
    simp only [word_prod', List.reverse_cons, word_prod_append, ih]
    congr 1
    simp [word_prod, Gen.matrix]

/-- Injectivity of the normal-form map `(k, ℓ, m) ↦ H3_normal k ℓ m`. -/
theorem H3_normal_inj {k ℓ m k' ℓ' m' : ℤ}
    (h : H3_normal k ℓ m = H3_normal k' ℓ' m') :
    k = k' ∧ ℓ = ℓ' ∧ m = m' := by
  have h21 := congrArg (fun M : Matrix (Fin 3) (Fin 3) ℤ => M 1 0) h
  have h32 := congrArg (fun M : Matrix (Fin 3) (Fin 3) ℤ => M 2 1) h
  have h31 := congrArg (fun M : Matrix (Fin 3) (Fin 3) ℤ => M 2 0) h
  simp [H3_normal] at h21 h32 h31
  exact ⟨h21, h32, h31⟩

/-- Induction on words read left-to-right (via `word_prod'`):
every word of length `N` produces a normal form with `|k|+|ℓ| ≤ N` and `|m| ≤ N²`. -/
theorem word_prod'_bounds (w : List Gen) :
    ∃ k ℓ m : ℤ,
      word_prod' w = H3_normal k ℓ m ∧
      k.natAbs + ℓ.natAbs ≤ w.length ∧ m.natAbs ≤ w.length * w.length := by
  induction w with
  | nil =>
    refine ⟨0, 0, 0, ?_, ?_, ?_⟩
    · simp [word_prod', H3_normal_zero]
    · simp
    · simp
  | cons g rest ih =>
    obtain ⟨k, ℓ, m, heq, hkl, hm⟩ := ih
    simp only [word_prod', heq]
    -- Case-split on g
    cases g with
    | sG =>
      refine ⟨k + 1, ℓ, m + ℓ, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_S_one k ℓ m
      · have h1 : (k + 1).natAbs ≤ k.natAbs + 1 := by
          have := @Int.natAbs_add_le k 1
          simpa using this
        simp [List.length_cons]
        omega
      · have h1 : (m + ℓ).natAbs ≤ m.natAbs + ℓ.natAbs := Int.natAbs_add_le _ _
        have h_len_sq : (rest.length + 1) * (rest.length + 1)
            = rest.length * rest.length + 2 * rest.length + 1 := by ring
        have hℓ : ℓ.natAbs ≤ rest.length := by omega
        simp [List.length_cons]
        calc (m + ℓ).natAbs
            ≤ m.natAbs + ℓ.natAbs := h1
          _ ≤ rest.length * rest.length + rest.length := by omega
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith
    | sInv =>
      refine ⟨k - 1, ℓ, m - ℓ, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_S_negone k ℓ m
      · have h1 : (k - 1).natAbs ≤ k.natAbs + 1 := by
          have := @Int.natAbs_sub_le k 1
          simpa using this
        simp [List.length_cons]
        omega
      · have h1 : (m - ℓ).natAbs ≤ m.natAbs + ℓ.natAbs := by
          have := @Int.natAbs_sub_le m ℓ
          exact this
        have hℓ : ℓ.natAbs ≤ rest.length := by omega
        simp [List.length_cons]
        calc (m - ℓ).natAbs
            ≤ m.natAbs + ℓ.natAbs := h1
          _ ≤ rest.length * rest.length + rest.length := by omega
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith
    | tG =>
      refine ⟨k, ℓ + 1, m, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_T_one k ℓ m
      · have h1 : (ℓ + 1).natAbs ≤ ℓ.natAbs + 1 := by
          have := @Int.natAbs_add_le ℓ 1
          simpa using this
        simp [List.length_cons]
        omega
      · simp [List.length_cons]
        calc m.natAbs
            ≤ rest.length * rest.length := hm
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith
    | tInv =>
      refine ⟨k, ℓ - 1, m, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_T_negone k ℓ m
      · have h1 : (ℓ - 1).natAbs ≤ ℓ.natAbs + 1 := by
          have := @Int.natAbs_sub_le ℓ 1
          simpa using this
        simp [List.length_cons]
        omega
      · simp [List.length_cons]
        calc m.natAbs
            ≤ rest.length * rest.length := hm
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith
    | uG =>
      refine ⟨k, ℓ, m + 1, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_U_one k ℓ m
      · simp [List.length_cons]; omega
      · have h1 : (m + 1).natAbs ≤ m.natAbs + 1 := by
          have := @Int.natAbs_add_le m 1
          simpa using this
        simp [List.length_cons]
        calc (m + 1).natAbs
            ≤ m.natAbs + 1 := h1
          _ ≤ rest.length * rest.length + 1 := by omega
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith
    | uInv =>
      refine ⟨k, ℓ, m - 1, ?_, ?_, ?_⟩
      · rw [Gen.matrix]; exact H3_normal_mul_U_negone k ℓ m
      · simp [List.length_cons]; omega
      · have h1 : (m - 1).natAbs ≤ m.natAbs + 1 := by
          have := @Int.natAbs_sub_le m 1
          simpa using this
        simp [List.length_cons]
        calc (m - 1).natAbs
            ≤ m.natAbs + 1 := h1
          _ ≤ rest.length * rest.length + 1 := by omega
          _ ≤ (rest.length + 1) * (rest.length + 1) := by nlinarith

/-- Every word representing `H3_normal k ℓ m` satisfies the bounds. -/
theorem word_length_bounds (k ℓ m : ℤ) :
    ∀ (w : List Gen), word_prod w = H3_normal k ℓ m →
      k.natAbs + ℓ.natAbs ≤ w.length ∧ m.natAbs ≤ w.length * w.length := by
  intro w hw
  have hrev : word_prod' w.reverse = H3_normal k ℓ m := by
    rw [← word_prod_reverse]
    simpa using hw
  obtain ⟨k', ℓ', m', heq', hkl', hm'⟩ := word_prod'_bounds w.reverse
  rw [hrev] at heq'
  obtain ⟨rfl, rfl, rfl⟩ := H3_normal_inj heq'.symm
  rw [List.length_reverse] at hkl' hm'
  exact ⟨hkl', hm'⟩

/-- **Q32.** Word-length lower bounds:
`|k| + |ℓ| ≤ |S^k T^ℓ U^m|` and `|m| ≤ |S^k T^ℓ U^m|²`. -/
theorem word_length_lower (k ℓ m : ℤ) :
    k.natAbs + ℓ.natAbs ≤ word_length (H3_normal k ℓ m) ∧
    m.natAbs ≤ word_length (H3_normal k ℓ m) * word_length (H3_normal k ℓ m) := by
  have hne : ∃ w : List Gen, word_prod w = H3_normal k ℓ m :=
    ⟨normalWord k ℓ m, normalWord_prod k ℓ m⟩
  obtain ⟨w, hw, hwlen⟩ := exists_word_of_word_length hne
  obtain ⟨h1, h2⟩ := word_length_bounds k ℓ m w hw
  rw [← hwlen]
  exact ⟨h1, h2⟩

/-- Combined lower bound: `|k| + |ℓ| + √|m| ≤ 2 · |S^k T^ℓ U^m|`. -/
theorem word_length_combined_lower (k ℓ m : ℤ) :
    k.natAbs + ℓ.natAbs + Nat.sqrt m.natAbs ≤ 2 * word_length (H3_normal k ℓ m) := by
  obtain ⟨hkl, hm⟩ := word_length_lower k ℓ m
  have hsqrt : Nat.sqrt m.natAbs ≤ word_length (H3_normal k ℓ m) := by
    -- m.natAbs ≤ N² means sqrt m.natAbs ≤ sqrt (N²) = N.
    have h1 : Nat.sqrt m.natAbs ≤ Nat.sqrt
        (word_length (H3_normal k ℓ m) * word_length (H3_normal k ℓ m)) :=
      Nat.sqrt_le_sqrt hm
    have h2 : Nat.sqrt (word_length (H3_normal k ℓ m) * word_length (H3_normal k ℓ m))
        = word_length (H3_normal k ℓ m) := by
      rw [show word_length (H3_normal k ℓ m) * word_length (H3_normal k ℓ m)
          = word_length (H3_normal k ℓ m) ^ 2 from by ring]
      exact Nat.sqrt_eq' _
    linarith [h1, h2]
  omega

/-! ### Q33 — Polynomial growth of degree 4 -/

/-- The ball of radius `R` restricted to matrices expressible by a word. -/
noncomputable def growthBallExpr (R : ℕ) :
    Set (Matrix (Fin 3) (Fin 3) ℤ) :=
  { M | (∃ w : List Gen, word_prod w = M) ∧ word_length M ≤ R }

/-- Ball membership via a normal form with bounded parameters. -/
theorem growthBallExpr_subset (R : ℕ) :
    growthBallExpr R ⊆ { M | ∃ k ℓ m : ℤ, M = H3_normal k ℓ m ∧
        k.natAbs ≤ R ∧ ℓ.natAbs ≤ R ∧ m.natAbs ≤ R * R } := by
  intro M hM
  obtain ⟨hne, hR⟩ := hM
  obtain ⟨w, hw, hwlen⟩ := exists_word_of_word_length hne
  have hrev : word_prod' w.reverse = M := by
    rw [← word_prod_reverse]
    simpa using hw
  obtain ⟨k, ℓ, m, heq, hkl, hm⟩ := word_prod'_bounds w.reverse
  rw [hrev] at heq
  refine ⟨k, ℓ, m, heq, ?_, ?_, ?_⟩
  · rw [List.length_reverse] at hkl
    have : w.length ≤ R := hwlen ▸ hR
    omega
  · rw [List.length_reverse] at hkl
    have : w.length ≤ R := hwlen ▸ hR
    omega
  · rw [List.length_reverse] at hm
    have hwR : w.length ≤ R := hwlen ▸ hR
    calc m.natAbs ≤ w.length * w.length := hm
      _ ≤ R * R := Nat.mul_le_mul hwR hwR

/-- Normal forms with small parameters lie in a ball of radius `8R`. -/
theorem H3_normal_in_growthBall (k ℓ m : ℤ) (R : ℕ)
    (hk : k.natAbs ≤ R) (hℓ : ℓ.natAbs ≤ R) (hm : m.natAbs ≤ R * R) :
    H3_normal k ℓ m ∈ growthBallExpr (8 * R) := by
  refine ⟨⟨normalWord k ℓ m, normalWord_prod k ℓ m⟩, ?_⟩
  have hsqrt : Nat.sqrt m.natAbs ≤ R := by
    have : Nat.sqrt m.natAbs ≤ Nat.sqrt (R * R) := Nat.sqrt_le_sqrt hm
    rwa [show Nat.sqrt (R * R) = R from ?_] at this
    · rw [show R * R = R ^ 2 from by ring]
      exact Nat.sqrt_eq' R
  calc word_length (H3_normal k ℓ m)
      ≤ k.natAbs + ℓ.natAbs + 6 * Nat.sqrt m.natAbs := word_length_upper k ℓ m
    _ ≤ R + R + 6 * R := by omega
    _ = 8 * R := by ring

/-! ### Lattice-box counting -/

/-- The lattice box `[-A, A]² × [-B, B]` as a `Finset (ℤ × ℤ × ℤ)`. -/
def latticeBox (A B : ℕ) : Finset (ℤ × ℤ × ℤ) :=
  (Finset.Icc (-(A : ℤ)) A) ×ˢ (Finset.Icc (-(A : ℤ)) A) ×ˢ (Finset.Icc (-(B : ℤ)) B)

theorem Icc_neg_card (n : ℕ) :
    (Finset.Icc (-(n : ℤ)) n).card = 2 * n + 1 := by
  rw [Int.card_Icc]
  have h : ((n : ℤ) + 1 - -(n : ℤ)).toNat = 2 * n + 1 := by
    have : ((n : ℤ) + 1 - -(n : ℤ)) = (2 * n + 1 : ℕ) := by push_cast; ring
    rw [this, Int.toNat_natCast]
  exact h

theorem latticeBox_card (A B : ℕ) :
    (latticeBox A B).card = (2 * A + 1) * (2 * A + 1) * (2 * B + 1) := by
  unfold latticeBox
  simp only [Finset.card_product, Icc_neg_card]
  ring

theorem mem_latticeBox_iff (A B : ℕ) (p : ℤ × ℤ × ℤ) :
    p ∈ latticeBox A B ↔ p.1.natAbs ≤ A ∧ p.2.1.natAbs ≤ A ∧ p.2.2.natAbs ≤ B := by
  unfold latticeBox
  simp only [Finset.mem_product, Finset.mem_Icc]
  constructor
  · rintro ⟨⟨h1a, h1b⟩, ⟨h2a, h2b⟩, ⟨h3a, h3b⟩⟩
    refine ⟨?_, ?_, ?_⟩ <;> omega
  · rintro ⟨h1, h2, h3⟩
    refine ⟨⟨?_, ?_⟩, ⟨?_, ?_⟩, ⟨?_, ?_⟩⟩ <;> omega

/-- The image of a `latticeBox` under `H3_normal` as a set. -/
noncomputable def normalImage (A B : ℕ) : Set (Matrix (Fin 3) (Fin 3) ℤ) :=
  (fun p : ℤ × ℤ × ℤ => H3_normal p.1 p.2.1 p.2.2) '' (latticeBox A B : Set (ℤ × ℤ × ℤ))

theorem normalImage_finite (A B : ℕ) : (normalImage A B).Finite :=
  Set.Finite.image _ (Finset.finite_toSet _)

theorem normalImage_ncard (A B : ℕ) :
    (normalImage A B).ncard = (2 * A + 1) * (2 * A + 1) * (2 * B + 1) := by
  unfold normalImage
  have hinj : Set.InjOn (fun p : ℤ × ℤ × ℤ => H3_normal p.1 p.2.1 p.2.2)
      (latticeBox A B : Set (ℤ × ℤ × ℤ)) := by
    intro p _ q _ h
    dsimp at h
    obtain ⟨h1, h2, h3⟩ := H3_normal_inj h
    ext <;> assumption
  rw [hinj.ncard_image, Set.ncard_coe_finset, latticeBox_card]

/-- The lattice box lower-bound witness: for `r := R/8`, all `H3_normal k ℓ m`
with `|k|, |ℓ| ≤ r`, `|m| ≤ r²` land in the ball of radius `R`. -/
theorem normalImage_subset_growthBall (R : ℕ) :
    normalImage (R / 8) ((R / 8) * (R / 8)) ⊆ growthBallExpr R := by
  intro M hM
  obtain ⟨p, hp, hM_eq⟩ := hM
  rw [Finset.mem_coe, mem_latticeBox_iff] at hp
  obtain ⟨hp1, hp2, hp3⟩ := hp
  subst hM_eq
  have h8 : 8 * (R / 8) ≤ R := by
    have := Nat.div_mul_le_self R 8
    linarith [this, show (R / 8) * 8 = 8 * (R / 8) from by ring]
  have hinc := H3_normal_in_growthBall p.1 p.2.1 p.2.2 (R / 8) hp1 hp2 hp3
  obtain ⟨hne, hlen⟩ := hinc
  refine ⟨hne, ?_⟩
  exact hlen.trans h8

/-- The upper-bound containment: every matrix in `growthBallExpr R` lies in
the image of `H3_normal` on the lattice box `[-R, R]² × [-R², R²]`. -/
theorem growthBallExpr_subset_normalImage (R : ℕ) :
    growthBallExpr R ⊆ normalImage R (R * R) := by
  intro M hM
  obtain ⟨k, ℓ, m, hM_eq, hk, hℓ, hm⟩ := growthBallExpr_subset R hM
  refine ⟨(k, ℓ, m), ?_, ?_⟩
  · rw [Finset.mem_coe, mem_latticeBox_iff]
    exact ⟨hk, hℓ, hm⟩
  · exact hM_eq.symm

theorem growthBallExpr_finite (R : ℕ) : (growthBallExpr R).Finite :=
  (normalImage_finite R (R * R)).subset (growthBallExpr_subset_normalImage R)

/-! ### Q33 — Polynomial growth of degree 4 -/

/-- **Q33.** Polynomial growth of degree 4 for `H_3(ℤ)`.

There exist constants `C₁, C₂ > 0` such that the cardinality of the word-length
ball of radius `R` lies between `C₁ · R⁴` and `C₂ · R⁴` for all `R ≥ 2`.

Proof: by `growthBallExpr_subset_normalImage`, the ball injects into a lattice
box of size `(2R+1)²(2R²+1) ≤ 27 R⁴ ≤ 10000 R⁴`. For the lower bound, with
`r := R/8`, the ball contains the image `H3_normal '' ([-r,r]² × [-r²,r²])` of
size `(2r+1)²(2r²+1)`, which for `R ≥ 8` dominates `R⁴/10000`, and for
`R ∈ [2, 7]` the identity alone yields `1 ≥ R⁴/10000` since `7⁴ = 2401`. -/
theorem heisenberg_growth_polynomial :
    ∃ (C₁ C₂ : ℝ), 0 < C₁ ∧ 0 < C₂ ∧ ∀ R : ℕ, 2 ≤ R →
      (C₁ * (R : ℝ)^4 ≤ (Nat.card (growthBallExpr R) : ℝ)) ∧
      ((Nat.card (growthBallExpr R) : ℝ) ≤ C₂ * (R : ℝ)^4) := by
  refine ⟨1 / 10000, 10000, by norm_num, by norm_num, ?_⟩
  intro R hR
  rw [Nat.card_coe_set_eq]
  refine ⟨?_, ?_⟩
  · -- Lower bound.
    -- The ball always contains the identity matrix (empty word), so its ncard ≥ 1.
    have hId : (1 : Matrix (Fin 3) (Fin 3) ℤ) ∈ growthBallExpr R := by
      refine ⟨⟨[], rfl⟩, ?_⟩
      have h0 : word_length (1 : Matrix (Fin 3) (Fin 3) ℤ) = 0 := by
        apply Nat.le_antisymm
        · exact word_length_le_of_word [] rfl
        · exact Nat.zero_le _
      rw [h0]; exact Nat.zero_le _
    have hOne_le : 1 ≤ (growthBallExpr R).ncard := by
      have hne : (growthBallExpr R).Nonempty := ⟨1, hId⟩
      exact (Set.ncard_pos (growthBallExpr_finite R)).mpr hne
    by_cases hR7 : R ≤ 7
    · -- For R ≤ 7, 1 ≤ ncard and R⁴/10000 ≤ 1.
      have hRR : (R : ℝ) ≤ 7 := by exact_mod_cast hR7
      have hRnn : (0 : ℝ) ≤ R := by exact_mod_cast (Nat.zero_le R)
      have hR4 : (R : ℝ)^4 ≤ 10000 := by
        have h7 : (R : ℝ)^4 ≤ 7^4 := by
          have := pow_le_pow_left₀ hRnn hRR 4
          convert this using 1
        have : (7 : ℝ)^4 = 2401 := by norm_num
        linarith
      have : (1 / 10000 : ℝ) * (R : ℝ)^4 ≤ 1 := by linarith
      calc (1 / 10000 : ℝ) * (R : ℝ)^4
          ≤ 1 := this
        _ ≤ ((growthBallExpr R).ncard : ℝ) := by exact_mod_cast hOne_le
    · -- For R ≥ 8, use the subset argument with r := R/8 ≥ 1.
      push_neg at hR7
      have hR8 : 8 ≤ R := hR7
      set r : ℕ := R / 8 with hr_def
      have hr_pos : 1 ≤ r := by
        rw [hr_def]
        exact Nat.one_le_div_iff (by norm_num : (0:ℕ) < 8) |>.mpr hR8
      have h8r : 8 * r ≤ R := by
        have := Nat.div_mul_le_self R 8
        linarith [this, show r * 8 = 8 * r from by ring]
      -- The image has cardinality (2r+1)²(2r²+1).
      have hsub : normalImage r (r * r) ⊆ growthBallExpr R :=
        normalImage_subset_growthBall R
      have hncard_sub : (normalImage r (r * r)).ncard ≤ (growthBallExpr R).ncard :=
        Set.ncard_le_ncard hsub (growthBallExpr_finite R)
      have himg_card : (normalImage r (r * r)).ncard
          = (2 * r + 1) * (2 * r + 1) * (2 * (r * r) + 1) :=
        normalImage_ncard r (r * r)
      -- Bound R⁴ ≤ 10000 · (2r+1)²(2r²+1).
      -- Use R ≤ 8r + 7, and for r ≥ 1, (2r+1)²(2r²+1) ≥ 9 · 3 = 27, growing fast.
      have hR_bound_nat : R ≤ 8 * r + 7 := by
        -- r = R / 8, so R = 8r + (R % 8) ≤ 8r + 7.
        have h1 : R = 8 * r + R % 8 := by
          rw [hr_def]
          exact (Nat.div_add_mod R 8).symm |>.trans (by ring)
        have h2 : R % 8 < 8 := Nat.mod_lt R (by norm_num)
        omega
      have hR_bound : (R : ℝ) ≤ 8 * r + 7 := by exact_mod_cast hR_bound_nat
      -- Key estimate: R⁴ ≤ 10000 · (2r+1)²(2r²+1) when r ≥ 1.
      have hR4_bound : (R : ℝ)^4 ≤ 10000 * ((2 * r + 1) * (2 * r + 1) * (2 * (r * r) + 1)) := by
        have hrR : (1 : ℝ) ≤ r := by exact_mod_cast hr_pos
        have hrnn : (0 : ℝ) ≤ r := by positivity
        have hRnn : (0 : ℝ) ≤ R := by positivity
        -- R ≤ 8r + 7 ≤ 15r (since r ≥ 1, so 7 ≤ 7r).
        have hRlt : (R : ℝ) ≤ 15 * r := by
          have : (7 : ℝ) ≤ 7 * r := by linarith
          linarith [hR_bound]
        -- R⁴ ≤ (15r)⁴ = 50625 r⁴
        have hR4 : (R : ℝ)^4 ≤ 50625 * r^4 := by
          have h0 : (0 : ℝ) ≤ 15 * r := by linarith
          have := pow_le_pow_left₀ hRnn hRlt 4
          calc (R : ℝ)^4 ≤ (15 * r)^4 := this
            _ = 50625 * r^4 := by ring
        -- (2r+1)² ≥ (2r)² = 4r² for r ≥ 0. And (2r²+1) ≥ 2r². So product ≥ 8r⁴.
        have hbox : (8 : ℝ) * (r : ℝ)^4
            ≤ ((2 * (r : ℝ) + 1) * (2 * r + 1) * (2 * (r * r) + 1)) := by
          nlinarith [hrnn, sq_nonneg ((r : ℝ)), sq_nonneg ((2 * (r:ℝ) + 1))]
        -- Target: R⁴ ≤ 10000 · (2r+1)²(2r²+1).
        have hgoal : ((2 * r + 1) * (2 * r + 1) * (2 * (r * r) + 1) : ℝ)
            = (2 * (r : ℝ) + 1) * (2 * r + 1) * (2 * (r * r) + 1) := by push_cast; ring
        rw [hgoal]
        -- So 10000 * (2r+1)²(2r²+1) ≥ 10000 · 8 r⁴ = 80000 r⁴ ≥ 50625 r⁴ ≥ R⁴.
        calc (R : ℝ)^4
            ≤ 50625 * r^4 := hR4
          _ ≤ 80000 * r^4 := by nlinarith [show (0 : ℝ) ≤ (r:ℝ)^4 from by positivity]
          _ = 10000 * (8 * (r : ℝ)^4) := by ring
          _ ≤ 10000 * ((2 * (r : ℝ) + 1) * (2 * r + 1) * (2 * (r * r) + 1)) := by
              nlinarith [hbox]
      have : (1 / 10000 : ℝ) * (R : ℝ)^4
          ≤ ((2 * r + 1) * (2 * r + 1) * (2 * (r * r) + 1) : ℝ) := by
        linarith
      calc (1 / 10000 : ℝ) * (R : ℝ)^4
          ≤ ((2 * r + 1) * (2 * r + 1) * (2 * (r * r) + 1) : ℝ) := this
        _ = ((normalImage r (r * r)).ncard : ℝ) := by
            rw [himg_card]; push_cast; ring
        _ ≤ ((growthBallExpr R).ncard : ℝ) := by exact_mod_cast hncard_sub
  · -- Upper bound.
    have hsub : growthBallExpr R ⊆ normalImage R (R * R) :=
      growthBallExpr_subset_normalImage R
    have hncard_sub : (growthBallExpr R).ncard ≤ (normalImage R (R * R)).ncard :=
      Set.ncard_le_ncard hsub (normalImage_finite R (R * R))
    have himg_card : (normalImage R (R * R)).ncard
        = (2 * R + 1) * (2 * R + 1) * (2 * (R * R) + 1) :=
      normalImage_ncard R (R * R)
    -- Bound (2R+1)²(2R²+1) ≤ 10000 R⁴ for R ≥ 2.
    have hRR : (2 : ℝ) ≤ R := by exact_mod_cast hR
    have hRnn : (0 : ℝ) ≤ R := by linarith
    have hR2 : (1 : ℝ) ≤ R^2 := by nlinarith
    have hbound : ((2 * R + 1) * (2 * R + 1) * (2 * (R * R) + 1) : ℝ)
        ≤ 10000 * R^4 := by
      -- (2R+1)² ≤ (3R)² = 9R² for R ≥ 1 (since 2R+1 ≤ 3R iff R ≥ 1).
      -- (2R²+1) ≤ 3R² for R ≥ 1 (since R² ≥ 1).
      -- Product ≤ 27 R⁴ ≤ 10000 R⁴.
      have h1 : (2 * R + 1 : ℝ) ≤ 3 * R := by linarith
      have h2 : (0 : ℝ) ≤ 2 * R + 1 := by linarith
      have h3 : (2 * R + 1 : ℝ) * (2 * R + 1) ≤ (3 * R) * (3 * R) := by
        nlinarith [h1, h2]
      have h4 : (2 * (R * R) + 1 : ℝ) ≤ 3 * R^2 := by nlinarith
      have h5 : (0 : ℝ) ≤ (2 * R + 1) * (2 * R + 1) := by nlinarith
      calc ((2 * R + 1) * (2 * R + 1) * (2 * (R * R) + 1) : ℝ)
          ≤ (3 * R) * (3 * R) * (3 * R^2) := by
            have := mul_le_mul h3 h4 (by linarith) (by nlinarith [h1])
            convert this using 1
      _ = 27 * R^4 := by ring
      _ ≤ 10000 * R^4 := by nlinarith [sq_nonneg ((R:ℝ)^2)]
    calc ((growthBallExpr R).ncard : ℝ)
        ≤ ((normalImage R (R * R)).ncard : ℝ) := by exact_mod_cast hncard_sub
      _ = ((2 * R + 1) * (2 * R + 1) * (2 * (R * R) + 1) : ℝ) := by
          rw [himg_card]; push_cast; ring
      _ ≤ 10000 * R^4 := hbound

end EnsX2026.Heisenberg
